@Library('jenkins-shared-library@feature/giulio-testing') _

theMultiPipeline(
    folders: [
        client: [
            _defaults: 'base',
            project: 'web',
            stages: [
6               dockerise: [
7                   steps: [
8                       'echo "No need to dockerise"'
9                   ]
10              ]
            ]
        ],
        server: [
            _defaults: 'base',
            project: 'web',
            stages: [
6               dockerise: [
7                   steps: [
8                       'echo "No need to dockerise"'
9                   ]
10              ]
            ]
        ]
    ]
)